
title: Henry's Resume
url: 'http://webjeda.com'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Henry Han
tagline: Full Stack Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: hanhenry88@outlook.com
phone: 770 906 0527
website: blog.webjeda.com #do not add http://
linkedin: alandoe
github: HHenry88
twitter: '@none'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
